title: Senderos y rutas escritas por locales de los andes colombias
logo: /images/andesLogoSmall.png
owner: juan gabriel
email: rutasdelosandes@gmail.com
description: descubre hermosas y poco conocidas rutas en los andes colombianos, evade multitudes en el camino y descubre las mas bellas especies y paisajes en tus rutas de senderismo
baseurl: "" # the subpath of your site, e.g. /blog
lang: es
url: http://rutasdelosandes.com # the base hostname & protocol for your site, e.g. http://example.com
alternative_lang: en
alternative_url: http://hikingintheandes.com # alternative version
fbpage: https://www.facebook.com/rutasdelosandes0/
github: https://github.com/jg-rc/rutasdelosandes/edit/master
twitter_username: _jgrc_
googlemaps_key: AIzaSyAz1r9qDIaA7lGoMdW7VPpvic7JXZjCdls
google_analytics: UA-100391485-2
instant_pages: 1078600055607267
#permalink built in style
permalink: /:categories/:title
disqus:
  shortname: takeahike-1
#jekyll seo tag

twitter:
  username: _jgrc_

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

