[build]
  # This will be run the site build
  command = "npm run build"
  # This is the directory is publishing to netlify's CDN
  publish = "_site/"
  # functions build directory
  functions = "functions/" # path to your functions directory
[[redirects]]
  from = "/"
  to = "/.netlify/functions/server"
  status = 200
  force = true
[[redirects]]
  from = "/javascript/*"
  to = "/javascript/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/amp/*"
  to = "/amp/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  force = false
  status = 200
